/*******************************************************************************
 *                                                                             *
 * This font definition file is generated by FontGen v3.0.1 - Unicode Grayscale +Bin *
 *              by Bahri Okuroglu - fontgen@dreamsware.info                    *
 *                                  http://dreamsware.info                     *
 *                                                                             *
 * Make sure it is legal to use installed fonts on your PC for this conversion *
 *                                                                             *
 * Font definition for Times New Roman 8                                       *
 *          bold: y                                                            *
 *          italic: n                                                          *
 *          underline: n                                                       *
 *          strikeout: n                                                       *
 *          direction: 0                                                       *
 *          compact vertical: n                                                *
 *          compact horizontal: y                                              *
 *          flip X: n                                                          *
 *          flip Y: n                                                          *
 *          1-bit grayscale (color=~pixel>>7)                                  *
 *          Current code page: windows-1252: ANSI Latin 1; Western European (Windows) *
 *          Dots per inch:  96                                                 *
 *                                                                             *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS' *
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,       *
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR      *
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR          *
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,       *
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,         *
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; *
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,    *
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR     *
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF      *
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE                                   *
 *******************************************************************************/


#include "fontgen.h"


#include "Times_New_Roman_8_n_bnnn_0_nh.h"



const fuint8  font_Times_New_Roman_8_n_bnnn_0_nh_width_table[];
const fuint8  font_Times_New_Roman_8_n_bnnn_0_nh_black_width_table[];
const fint8   font_Times_New_Roman_8_n_bnnn_0_nh_origin_x_table[];
const fuint8  font_Times_New_Roman_8_n_bnnn_0_nh_glyph_table[];
#ifdef FONTGEN_USE_MAPPING_TABLE
const fuint8  font_Times_New_Roman_8_n_bnnn_0_nh_mapping_table[];
#endif
#ifdef FONTGEN_USE_PRECALCULATED_OFFSETS
const font_offset_t font_Times_New_Roman_8_n_bnnn_0_nh_offset_table[];
#endif


/*
   Unicode to current codepage codes:
   ----------------------------------
   User requested to care current codepage of Windows. So, unicode character 
   codes are converted to the codes which is used by the current code page 
   (windows-1252: ANSI Latin 1; Western European (Windows) ) whenever possible. 
   
   This conversion is quite helpful when your codepage is different than the
   standart ASCII code table, and using those characters in your strings in 
   your IDE which is not in the ASCII code table.
   
   Consider you're using MS Windows for Turkey, with the current codepage
   'windows-1254: ANSI Turkish; Turkish (Windows)'; and want to use the Turkish
   characters on your LCD interface. 
   
   Consider the 'I' character with a dot above. Its unicode code is 0x0130.
   Its code in the windows1254 codepage is 0xDD. When I create a string with
   this character in it, the IDE will put 0xDD for the character. When you 
   address the FontGen tables with 0xDD, you'll reach to a wrong or invalid glyph.
   
   When the 'care codepage' option is checked, FontGen will use 0xDD instead of 
   0x0130 for all occurences of this character. This will fix the problem 
   described above.
 */
   


const FONT_DEF Times_New_Roman_8_n_bnnn_0_nh = {
#ifdef FONTGEN_HAVE_VERSION
   4, 	/* Version of the image definition format */
#ifdef FONTGEN_FIT_TO_16BIT_BOUNDARY
   0, 	/* filler for 16 bit boundary alignment   */
#endif
#endif
   13, 	/* glyph_height */
   0, 	/* glyph_width (this font has variable width for each glyph.)
      	   Check the below array for the width of the glyphs */
   (fuint8 *)font_Times_New_Roman_8_n_bnnn_0_nh_width_table,
   NULL, /* black height table */
   (fuint8 *)font_Times_New_Roman_8_n_bnnn_0_nh_black_width_table, /* black width table */
   NULL, /* origin Y table */
   (fint8  *)font_Times_New_Roman_8_n_bnnn_0_nh_origin_x_table, /* origin X table */
#ifdef FONTGEN_HAVE_MINMAX_Y
   1, /* minimum origin Y over all characters in this character set */
   13, /* maximum ending point of black area (origin_y + black_height) over all characters in this character set */
#endif
#ifdef FONTGEN_HAVE_MINMAX_X
   -1, /* minimum origin X over all characters in this character set */
   7, /* maximum ending point of black area (origin_x + black_width) over all characters in this character set */
#endif
   (fuint8 *)font_Times_New_Roman_8_n_bnnn_0_nh_glyph_table,
#ifdef FONTGEN_HAVE_MAPPING_TABLE 
#ifdef FONTGEN_USE_MAPPING_TABLE 
   (fuint8 *)font_Times_New_Roman_8_n_bnnn_0_nh_mapping_table,
#else
   NULL,
#endif
#endif 
#ifdef FONTGEN_HAVE_EXTENDED_MAPPING_TABLE 
#ifdef FONTGEN_USE_EXTENDED_MAPPING_TABLE 
   (fuint16 *)font_Times_New_Roman_8_n_bnnn_0_nh_extended_mapping_table,
#else
   NULL,
#endif
#endif 
#ifdef FONTGEN_HAVE_PRECALCULATED_OFFSETS
#ifdef FONTGEN_USE_PRECALCULATED_OFFSETS 
   (font_offset_t *)font_Times_New_Roman_8_n_bnnn_0_nh_offset_table,
#else 
   NULL, 
#endif 
#endif 
   28, 	/* number of glyphs in this font definition */
#ifdef FONTGEN_HAVE_FONT_DETAILS
   8, 	/* font size */
#endif
   0, 	/* rotation / 90 */
   1, 	/* color depth in bits */
#ifdef FONTGEN_HAVE_FONT_DETAILS
   1, 	/* bold? */
   0, 	/* italic? */
   0, 	/* underline? */
   0, 	/* strikeout? */
   0, 	/* flipX? */
   0, 	/* flipY? */
   0  	/* reverse? */
#endif
};



/* Following table provides the width information in pixels for each character
   selected.
   
   You should index this array with the index of the char in your character set.
   This can be calculated with a simple mathematical expression if you have such
   a simple expression, or you can use the mapping table for this purpose.
   
   To find the width of a glyph in font_Times_New_Roman_8_n_bnnn_0_nh_width_table[],
   use the following expression:
   	font_Times_New_Roman_8_n_bnnn_0_nh_width_table[font_Times_New_Roman_8_n_bnnn_0_nh_offset_table[c]]
   where 'c' is the variable holding the character you're interested in
   
   This table is produced only for the variable width fonts. For the fixed width
   fonts, you should use the width information in FONT_DEF struct.
 */
const fuint8 font_Times_New_Roman_8_n_bnnn_0_nh_width_table[] = {
/*		width  char hexcode*/
/*		=====  ==== =======*/
		 6, /* '.' 0x06F0*/
		 6, /* '.' 0x06F1*/
		 6, /* '.' 0x06F2*/
		 6, /* '.' 0x06F3*/
		 6, /* '.' 0x06F4*/
		 6, /* '.' 0x06F5*/
		 6, /* '.' 0x06F6*/
		 6, /* '.' 0x06F7*/
		 6, /* '.' 0x06F8*/
		 6, /* '.' 0x06F9*/
		 3, /* '.' 0x0622*/
		 2, /* '.' 0x0627*/
		 5, /* '.' 0x0621*/
		 3, /* '.' 0xFE8E*/
		 3, /* '.' 0xFE91*/
		 7, /* '.' 0x0628*/
		 3, /* '.' 0xFB58*/
		 7, /* '.' 0x067E*/
		 3, /* '.' 0xFE97*/
		 7, /* '.' 0x062A*/
		 3, /* '.' 0xFE9B*/
		 7, /* '.' 0x062B*/
		 6, /* '.' 0xFE9F*/
		 6, /* '.' 0xFE9E*/
		 6, /* '.' 0x062C*/
		 6, /* '.' 0xFB7C*/
		 6, /* '.' 0xFB7B*/
		 6, /* '.' 0x0686*/
};










/* Following is the array holding the width of each glyph's black area. 
   While the width of the black area is generally less than the width of the 
   glyphs, it can be greater than it also. Glyph for char 'f' (Time New Roman Italic) 
   is such a case. In the compact horizontal mode, only the black area is 
   dumped to the font definition file. 
 */
const fuint8 font_Times_New_Roman_8_n_bnnn_0_nh_black_width_table[] = {
/*		black_width     char  hexcode*/
/*		===========     ====  =======*/
		  2,          /* '.'  0x06F0 */
		  3,          /* '.'  0x06F1 */
		  4,          /* '.'  0x06F2 */
		  6,          /* '.'  0x06F3 */
		  5,          /* '.'  0x06F4 */
		  4,          /* '.'  0x06F5 */
		  4,          /* '.'  0x06F6 */
		  5,          /* '.'  0x06F7 */
		  4,          /* '.'  0x06F8 */
		  4,          /* '.'  0x06F9 */
		  3,          /* '.'  0x0622 */
		  2,          /* '.'  0x0627 */
		  5,          /* '.'  0x0621 */
		  3,          /* '.'  0xFE8E */
		  4,          /* '.'  0xFE91 */
		  7,          /* '.'  0x0628 */
		  4,          /* '.'  0xFB58 */
		  7,          /* '.'  0x067E */
		  4,          /* '.'  0xFE97 */
		  7,          /* '.'  0x062A */
		  4,          /* '.'  0xFE9B */
		  7,          /* '.'  0x062B */
		  7,          /* '.'  0xFE9F */
		  7,          /* '.'  0xFE9E */
		  7,          /* '.'  0x062C */
		  7,          /* '.'  0xFB7C */
		  7,          /* '.'  0xFB7B */
		  7,          /* '.'  0x0686 */
};


/* Following is the array holding the X part of the origin point (top-left) for 
   the black area of the glyph. While this value is positive in general 
   (meaning that we have empty columns at the left of the glyph), it can be 
   negative for some cases. This is called as overhang. The overhang is 
   the part of the ink of a glyph that extends beyond the advance width of 
   the glyph. Most glyphs (such as 'H') have no overhang, as there is a 
   little white space on either side to separate them from adjacent glyphs. 
   An example of a glyph with overhang is the italic 'f' for Times New Roman.
   
   Another example for overhang is some non-latin language glyphs like Devanagari. 
   For Devanagari, some glyphs (like 0x0941) are printed above or below of 
   the previous glpyh printed, which means they have 0 advance width at all. 
 */
const fint8 font_Times_New_Roman_8_n_bnnn_0_nh_origin_x_table[] = {
/*		origin_x     char  hexcode*/
/*		========     ====  =======*/
		  2,       /* '.'  0x06F0 */
		  1,       /* '.'  0x06F1 */
		  1,       /* '.'  0x06F2 */
		  0,       /* '.'  0x06F3 */
		  0,       /* '.'  0x06F4 */
		  1,       /* '.'  0x06F5 */
		  1,       /* '.'  0x06F6 */
		  0,       /* '.'  0x06F7 */
		  1,       /* '.'  0x06F8 */
		  1,       /* '.'  0x06F9 */
		  0,       /* '.'  0x0622 */
		  0,       /* '.'  0x0627 */
		  0,       /* '.'  0x0621 */
		  0,       /* '.'  0xFE8E */
		 -1,       /* '.'  0xFE91 */
		  0,       /* '.'  0x0628 */
		 -1,       /* '.'  0xFB58 */
		  0,       /* '.'  0x067E */
		 -1,       /* '.'  0xFE97 */
		  0,       /* '.'  0x062A */
		 -1,       /* '.'  0xFE9B */
		  0,       /* '.'  0x062B */
		 -1,       /* '.'  0xFE9F */
		  0,       /* '.'  0xFE9E */
		  0,       /* '.'  0x062C */
		 -1,       /* '.'  0xFB7C */
		  0,       /* '.'  0xFB7B */
		  0,       /* '.'  0x0686 */
};


#ifdef FONTGEN_USE_MAPPING_TABLE
/* Following array provides the mapping for the characters in the ASCII 
   character set to your character set.
   
   Consider you've selected characters A-Z, 0-9 to produce the font definition for.
   With this selection, in the offset, detail and width tables, the first entry 
   will be for the character 'A', since it is your first char. And the 26. entry
   will be for the char '0'.
   
   In the micro, you'll need to address these tables at run time; therefore you'll
   need the mapping of ASCII character set to your character set. If you can find
   a simple mathematical expression for this mapping, you can use that. For the
   above character set, you can use the following mathematical expression for
   this mapping:
   	offset(c): (c>'A')?(c-'A'):(c-'0'+'Z'-'A'+1)
   
   If you do not have such a mathematical expression of you do not want to get tied
   to such an expression, you can use the following mapping table.
   
   This table is indexed with the ASCII character set, and returns the index 
   for your character set. If you do not have the given ASCII char in your charset
   it will return 0 always. This means that if you try to print a char 
   which you have not prepared the font for, you'll print the first char in your
   charset.
   
   If you want to find the offset for char 'A', use the following code:
   	font_Times_New_Roman_8_n_bnnn_0_nh_offset_table[font_Times_New_Roman_8_n_bnnn_0_nh_mapping_table['A']]
   
   If you do not want to use this mapping table, undefine FONTGEN_USE_MAPPING_TABLE
   to reduce the code size
   
   If you're generating multiple font definition files for the same character set
   to use in the same project, a single mapping file is adequate for all those
   definition files. You can remove all others to save space, but you need to
   update the other font definition files to point to the only one mapping table.
   

   Note for unicode version:
   =========================
      If you're generating font definition for the characters from a single
      code page, you can use the mapping table as following:
         font_Times_New_Roman_8_n_bnnn_0_nh_offset_table[font_Times_New_Roman_8_n_bnnn_0_nh_mapping_table[unicode_glpyh & 0x00FF]]
      
      If you're generating font definition for the glpyhs from different code
      pages, there is a risk of collision in the mapping table. Consider that
      you're using chars 0x0612 and 0x0712. Both of these glpyhs would map to
      slot 0x12.
      
      If you're generating font definition for more than 256 glpyhs, extend the
      mapping table by hand.
      
      If there is a risk of collision because of using glyphs from different
      code pages, check the mapping table manually to fix the collision.
      
      If you do not want to make manual changes, you can use the 
      font_Times_New_Roman_8_n_bnnn_0_nh_extended_mapping table below.
 */
const fuint8 font_Times_New_Roman_8_n_bnnn_0_nh_mapping_table[] = {
/*		map  hexcode decimal char ('.' is printed for the unprintable characters) */
/*		===  ======= ======= ==== */
		  0, /* 00 -   0    - '.' */
		  0, /* 01 -   1    - '.' */
		  0, /* 02 -   2    - '.' */
		  0, /* 03 -   3    - '.' */
		  0, /* 04 -   4    - '.' */
		  0, /* 05 -   5    - '.' */
		  0, /* 06 -   6    - '.' */
		  0, /* 07 -   7    - '.' */
		  0, /* 08 -   8    - '.' */
		  0, /* 09 -   9    - '.' */
		  0, /* 0A -  10    - '.' */
		  0, /* 0B -  11    - '.' */
		  0, /* 0C -  12    - '.' */
		  0, /* 0D -  13    - '.' */
		  0, /* 0E -  14    - '.' */
		  0, /* 0F -  15    - '.' */
		  0, /* 10 -  16    - '.' */
		  0, /* 11 -  17    - '.' */
		  0, /* 12 -  18    - '.' */
		  0, /* 13 -  19    - '.' */
		  0, /* 14 -  20    - '.' */
		  0, /* 15 -  21    - '.' */
		  0, /* 16 -  22    - '.' */
		  0, /* 17 -  23    - '.' */
		  0, /* 18 -  24    - '.' */
		  0, /* 19 -  25    - '.' */
		  0, /* 1A -  26    - '.' */
		  0, /* 1B -  27    - '.' */
		  0, /* 1C -  28    - '.' */
		  0, /* 1D -  29    - '.' */
		  0, /* 1E -  30    - '.' */
		  0, /* 1F -  31    - '.' */
		  0, /* 20 -  32    - ' ' */
		 12, /* 21 -  33    - '!' */
		 10, /* 22 -  34    - '"' */
		  0, /* 23 -  35    - '#' */
		  0, /* 24 -  36    - '$' */
		  0, /* 25 -  37    - '%' */
		  0, /* 26 -  38    - '&' */
		 11, /* 27 -  39    - ''' */
		 15, /* 28 -  40    - '(' */
		  0, /* 29 -  41    - ')' */
		 19, /* 2A -  42    - '*' */
		 21, /* 2B -  43    - '+' */
		 24, /* 2C -  44    - ',' */
		  0, /* 2D -  45    - '-' */
		  0, /* 2E -  46    - '.' */
		  0, /* 2F -  47    - '/' */
		  0, /* 30 -  48    - '0' */
		  0, /* 31 -  49    - '1' */
		  0, /* 32 -  50    - '2' */
		  0, /* 33 -  51    - '3' */
		  0, /* 34 -  52    - '4' */
		  0, /* 35 -  53    - '5' */
		  0, /* 36 -  54    - '6' */
		  0, /* 37 -  55    - '7' */
		  0, /* 38 -  56    - '8' */
		  0, /* 39 -  57    - '9' */
		  0, /* 3A -  58    - ':' */
		  0, /* 3B -  59    - ';' */
		  0, /* 3C -  60    - '<' */
		  0, /* 3D -  61    - '=' */
		  0, /* 3E -  62    - '>' */
		  0, /* 3F -  63    - '?' */
		  0, /* 40 -  64    - '@' */
		  0, /* 41 -  65    - 'A' */
		  0, /* 42 -  66    - 'B' */
		  0, /* 43 -  67    - 'C' */
		  0, /* 44 -  68    - 'D' */
		  0, /* 45 -  69    - 'E' */
		  0, /* 46 -  70    - 'F' */
		  0, /* 47 -  71    - 'G' */
		  0, /* 48 -  72    - 'H' */
		  0, /* 49 -  73    - 'I' */
		  0, /* 4A -  74    - 'J' */
		  0, /* 4B -  75    - 'K' */
		  0, /* 4C -  76    - 'L' */
		  0, /* 4D -  77    - 'M' */
		  0, /* 4E -  78    - 'N' */
		  0, /* 4F -  79    - 'O' */
		  0, /* 50 -  80    - 'P' */
		  0, /* 51 -  81    - 'Q' */
		  0, /* 52 -  82    - 'R' */
		  0, /* 53 -  83    - 'S' */
		  0, /* 54 -  84    - 'T' */
		  0, /* 55 -  85    - 'U' */
		  0, /* 56 -  86    - 'V' */
		  0, /* 57 -  87    - 'W' */
		 16, /* 58 -  88    - 'X' */
		  0, /* 59 -  89    - 'Y' */
		  0, /* 5A -  90    - 'Z' */
		  0, /* 5B -  91    - '[' */
		  0, /* 5C -  92    - '\' */
		  0, /* 5D -  93    - ']' */
		  0, /* 5E -  94    - '^' */
		  0, /* 5F -  95    - '_' */
		  0, /* 60 -  96    - '`' */
		  0, /* 61 -  97    - 'a' */
		  0, /* 62 -  98    - 'b' */
		  0, /* 63 -  99    - 'c' */
		  0, /* 64 - 100    - 'd' */
		  0, /* 65 - 101    - 'e' */
		  0, /* 66 - 102    - 'f' */
		  0, /* 67 - 103    - 'g' */
		  0, /* 68 - 104    - 'h' */
		  0, /* 69 - 105    - 'i' */
		  0, /* 6A - 106    - 'j' */
		  0, /* 6B - 107    - 'k' */
		  0, /* 6C - 108    - 'l' */
		  0, /* 6D - 109    - 'm' */
		  0, /* 6E - 110    - 'n' */
		  0, /* 6F - 111    - 'o' */
		  0, /* 70 - 112    - 'p' */
		  0, /* 71 - 113    - 'q' */
		  0, /* 72 - 114    - 'r' */
		  0, /* 73 - 115    - 's' */
		  0, /* 74 - 116    - 't' */
		  0, /* 75 - 117    - 'u' */
		  0, /* 76 - 118    - 'v' */
		  0, /* 77 - 119    - 'w' */
		  0, /* 78 - 120    - 'x' */
		  0, /* 79 - 121    - 'y' */
		  0, /* 7A - 122    - 'z' */
		 26, /* 7B - 123    - '{' */
		 25, /* 7C - 124    - '|' */
		  0, /* 7D - 125    - '}' */
		 17, /* 7E - 126    - '~' */
		  0, /* 7F - 127    - '' */
		  0, /* 80 - 128    - 'Ä' */
		  0, /* 81 - 129    - 'Å' */
		  0, /* 82 - 130    - 'Ç' */
		  0, /* 83 - 131    - 'É' */
		  0, /* 84 - 132    - 'Ñ' */
		  0, /* 85 - 133    - 'Ö' */
		 27, /* 86 - 134    - 'Ü' */
		  0, /* 87 - 135    - 'á' */
		  0, /* 88 - 136    - 'à' */
		  0, /* 89 - 137    - 'â' */
		  0, /* 8A - 138    - 'ä' */
		  0, /* 8B - 139    - 'ã' */
		  0, /* 8C - 140    - 'å' */
		  0, /* 8D - 141    - 'ç' */
		 13, /* 8E - 142    - 'é' */
		  0, /* 8F - 143    - 'è' */
		  0, /* 90 - 144    - 'ê' */
		 14, /* 91 - 145    - 'ë' */
		  0, /* 92 - 146    - 'í' */
		  0, /* 93 - 147    - 'ì' */
		  0, /* 94 - 148    - 'î' */
		  0, /* 95 - 149    - 'ï' */
		  0, /* 96 - 150    - 'ñ' */
		 18, /* 97 - 151    - 'ó' */
		  0, /* 98 - 152    - 'ò' */
		  0, /* 99 - 153    - 'ô' */
		  0, /* 9A - 154    - 'ö' */
		 20, /* 9B - 155    - 'õ' */
		  0, /* 9C - 156    - 'ú' */
		  0, /* 9D - 157    - 'ù' */
		 23, /* 9E - 158    - 'û' */
		 22, /* 9F - 159    - 'ü' */
		  0, /* A0 - 160    - '†' */
		  0, /* A1 - 161    - '°' */
		  0, /* A2 - 162    - '¢' */
		  0, /* A3 - 163    - '£' */
		  0, /* A4 - 164    - '§' */
		  0, /* A5 - 165    - '•' */
		  0, /* A6 - 166    - '¶' */
		  0, /* A7 - 167    - 'ß' */
		  0, /* A8 - 168    - '®' */
		  0, /* A9 - 169    - '©' */
		  0, /* AA - 170    - '™' */
		  0, /* AB - 171    - '´' */
		  0, /* AC - 172    - '¨' */
		  0, /* AD - 173    - '≠' */
		  0, /* AE - 174    - 'Æ' */
		  0, /* AF - 175    - 'Ø' */
		  0, /* B0 - 176    - '∞' */
		  0, /* B1 - 177    - '±' */
		  0, /* B2 - 178    - '≤' */
		  0, /* B3 - 179    - '≥' */
		  0, /* B4 - 180    - '¥' */
		  0, /* B5 - 181    - 'µ' */
		  0, /* B6 - 182    - '∂' */
		  0, /* B7 - 183    - '∑' */
		  0, /* B8 - 184    - '∏' */
		  0, /* B9 - 185    - 'π' */
		  0, /* BA - 186    - '∫' */
		  0, /* BB - 187    - 'ª' */
		  0, /* BC - 188    - 'º' */
		  0, /* BD - 189    - 'Ω' */
		  0, /* BE - 190    - 'æ' */
		  0, /* BF - 191    - 'ø' */
		  0, /* C0 - 192    - '¿' */
		  0, /* C1 - 193    - '¡' */
		  0, /* C2 - 194    - '¬' */
		  0, /* C3 - 195    - '√' */
		  0, /* C4 - 196    - 'ƒ' */
		  0, /* C5 - 197    - '≈' */
		  0, /* C6 - 198    - '∆' */
		  0, /* C7 - 199    - '«' */
		  0, /* C8 - 200    - '»' */
		  0, /* C9 - 201    - '…' */
		  0, /* CA - 202    - ' ' */
		  0, /* CB - 203    - 'À' */
		  0, /* CC - 204    - 'Ã' */
		  0, /* CD - 205    - 'Õ' */
		  0, /* CE - 206    - 'Œ' */
		  0, /* CF - 207    - 'œ' */
		  0, /* D0 - 208    - '–' */
		  0, /* D1 - 209    - '—' */
		  0, /* D2 - 210    - '“' */
		  0, /* D3 - 211    - '”' */
		  0, /* D4 - 212    - '‘' */
		  0, /* D5 - 213    - '’' */
		  0, /* D6 - 214    - '÷' */
		  0, /* D7 - 215    - '◊' */
		  0, /* D8 - 216    - 'ÿ' */
		  0, /* D9 - 217    - 'Ÿ' */
		  0, /* DA - 218    - '⁄' */
		  0, /* DB - 219    - '€' */
		  0, /* DC - 220    - '‹' */
		  0, /* DD - 221    - '›' */
		  0, /* DE - 222    - 'ﬁ' */
		  0, /* DF - 223    - 'ﬂ' */
		  0, /* E0 - 224    - '‡' */
		  0, /* E1 - 225    - '·' */
		  0, /* E2 - 226    - '‚' */
		  0, /* E3 - 227    - '„' */
		  0, /* E4 - 228    - '‰' */
		  0, /* E5 - 229    - 'Â' */
		  0, /* E6 - 230    - 'Ê' */
		  0, /* E7 - 231    - 'Á' */
		  0, /* E8 - 232    - 'Ë' */
		  0, /* E9 - 233    - 'È' */
		  0, /* EA - 234    - 'Í' */
		  0, /* EB - 235    - 'Î' */
		  0, /* EC - 236    - 'Ï' */
		  0, /* ED - 237    - 'Ì' */
		  0, /* EE - 238    - 'Ó' */
		  0, /* EF - 239    - 'Ô' */
		  0, /* F0 - 240    - '' */
		  1, /* F1 - 241    - 'Ò' */
		  2, /* F2 - 242    - 'Ú' */
		  3, /* F3 - 243    - 'Û' */
		  4, /* F4 - 244    - 'Ù' */
		  5, /* F5 - 245    - 'ı' */
		  6, /* F6 - 246    - 'ˆ' */
		  7, /* F7 - 247    - '˜' */
		  8, /* F8 - 248    - '¯' */
		  9, /* F9 - 249    - '˘' */
		  0, /* FA - 250    - '˙' */
		  0, /* FB - 251    - '˚' */
		  0, /* FC - 252    - '¸' */
		  0, /* FD - 253    - '˝' */
		  0, /* FE - 254    - '˛' */
		  0, /* FF - 255    - 'ˇ' */
};
#endif


#ifdef FONTGEN_USE_EXTENDED_MAPPING_TABLE
#error 'Extended mapping table generation is disabled from user interface of FontGen'
#endif
/* Following is the one dimensional flat array to hold the font information.
   
   Each byte holds the color information for the successive pixels.
   If the color_depth=1, then each byte will hold the color info (or set/reset)
   for 8 pixels. 
   
   Even it is a one-dimensional array, the representation is in matrix format,
   where each line is holding the color information of a line of the glyph.
   
   The starting offset of a given glyph can be calculated by code using the
   width and height information of the all characters before the given character.
   Or array font_Times_New_Roman_8_n_bnnn_0_nh_offset_table[] can be used for this purpose.
 */
const fuint8 font_Times_New_Roman_8_n_bnnn_0_nh_glyph_table[] = {
		/* char: '.' hexcode: 0x06F0 glyph_width: 6 black_width: 2 origin_x: 2 */
		0x00, 	/*  [  ]  */
		0x00, 	/*  [  ]  */
		0x00, 	/*  [  ]  */
		0x00, 	/*  [  ]  */
		0x00, 	/*  [  ]  */
		0x00, 	/*  [  ]  */
		0x40, 	/*  [ *]  */
		0x40, 	/*  [ *]  */
		0x00, 	/*  [  ]  */
		0x00, 	/*  [  ]  */
		0x00, 	/*  [  ]  */
		0x00, 	/*  [  ]  */
		0x00, 	/*  [  ]  */
		
		/* char: '.' hexcode: 0x06F1 glyph_width: 6 black_width: 3 origin_x: 1 */
		0x00, 	/*  [   ]  */
		0x00, 	/*  [   ]  */
		0x00, 	/*  [   ]  */
		0x00, 	/*  [   ]  */
		0x60, 	/*  [ **]  */
		0x20, 	/*  [  *]  */
		0x20, 	/*  [  *]  */
		0x20, 	/*  [  *]  */
		0x00, 	/*  [   ]  */
		0x00, 	/*  [   ]  */
		0x00, 	/*  [   ]  */
		0x00, 	/*  [   ]  */
		0x00, 	/*  [   ]  */
		
		/* char: '.' hexcode: 0x06F2 glyph_width: 6 black_width: 4 origin_x: 1 */
		0x00, 	/*  [    ]  */
		0x00, 	/*  [    ]  */
		0x00, 	/*  [    ]  */
		0x10, 	/*  [   *]  */
		0x70, 	/*  [ ***]  */
		0x60, 	/*  [ ** ]  */
        0x20,     /*  [  * ]  */
        0x20,     /*  [  * ]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        
        /* char: '.' hexcode: 0x06F3 glyph_width: 6 black_width: 6 origin_x: 0 */
        0x00,     /*  [      ]  */
        0x00,     /*  [      ]  */
        0x00,     /*  [      ]  */
        0x10,     /*  [   *  ]  */
        0x78,     /*  [ **** ]  */
        0x38,     /*  [  *** ]  */
        0x20,     /*  [  *   ]  */
        0x00,     /*  [      ]  */
        0x00,     /*  [      ]  */
        0x00,     /*  [      ]  */
        0x00,     /*  [      ]  */
        0x00,     /*  [      ]  */
        0x00,     /*  [      ]  */
        
        /* char: '.' hexcode: 0x06F4 glyph_width: 6 black_width: 5 origin_x: 0 */
        0x00,     /*  [     ]  */
        0x00,     /*  [     ]  */
        0x00,     /*  [     ]  */
        0x18,     /*  [   **]  */
        0x70,     /*  [ *** ]  */
        0x38,     /*  [  ***]  */
        0x38,     /*  [  ***]  */
        0x00,     /*  [     ]  */
        0x00,     /*  [     ]  */
        0x00,     /*  [     ]  */
        0x00,     /*  [     ]  */
        0x00,     /*  [     ]  */
        0x00,     /*  [     ]  */
        
        /* char: '.' hexcode: 0x06F5 glyph_width: 6 black_width: 4 origin_x: 1 */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x20,     /*  [  * ]  */
        0x30,     /*  [  **]  */
        0x40,     /*  [ *  ]  */
        0xF0,     /*  [****]  */
        0x70,     /*  [ ***]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        
        /* char: '.' hexcode: 0x06F6 glyph_width: 6 black_width: 4 origin_x: 1 */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x30,     /*  [  **]  */
        0x40,     /*  [ *  ]  */
        0x70,     /*  [ ***]  */
        0x70,     /*  [ ***]  */
        0x20,     /*  [  * ]  */
        0x40,     /*  [ *  ]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        
        /* char: '.' hexcode: 0x06F7 glyph_width: 6 black_width: 5 origin_x: 0 */
        0x00,     /*  [     ]  */
        0x00,     /*  [     ]  */
        0x00,     /*  [     ]  */
        0x00,     /*  [     ]  */
        0x48,     /*  [ *  *]  */
        0x28,     /*  [  * *]  */
        0x20,     /*  [  *  ]  */
        0x10,     /*  [   * ]  */
        0x10,     /*  [   * ]  */
        0x00,     /*  [     ]  */
        0x00,     /*  [     ]  */
        0x00,     /*  [     ]  */
        0x00,     /*  [     ]  */
        
        /* char: '.' hexcode: 0x06F8 glyph_width: 6 black_width: 4 origin_x: 1 */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x20,     /*  [  * ]  */
        0x20,     /*  [  * ]  */
        0x40,     /*  [ *  ]  */
        0x50,     /*  [ * *]  */
        0x90,     /*  [*  *]  */
        0x80,     /*  [*   ]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        
        /* char: '.' hexcode: 0x06F9 glyph_width: 6 black_width: 4 origin_x: 1 */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x60,     /*  [ ** ]  */
        0x20,     /*  [  * ]  */
        0x60,     /*  [ ** ]  */
        0x60,     /*  [ ** ]  */
        0x10,     /*  [   *]  */
        0x10,     /*  [   *]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        
        /* char: '.' hexcode: 0x0622 glyph_width: 3 black_width: 3 origin_x: 0 */
        0x00,     /*  [   ]  */
        0x60,     /*  [ **]  */
        0x00,     /*  [   ]  */
        0x00,     /*  [   ]  */
        0x40,     /*  [ * ]  */
        0x00,     /*  [   ]  */
        0x00,     /*  [   ]  */
        0x00,     /*  [   ]  */
        0x00,     /*  [   ]  */
        0x00,     /*  [   ]  */
        0x00,     /*  [   ]  */
        0x00,     /*  [   ]  */
        0x00,     /*  [   ]  */
        
        /* char: '.' hexcode: 0x0627 glyph_width: 2 black_width: 2 origin_x: 0 */
        0x00,     /*  [  ]  */
        0x00,     /*  [  ]  */
        0x00,     /*  [  ]  */
        0x00,     /*  [  ]  */
        0x40,     /*  [ *]  */
        0x40,     /*  [ *]  */
        0x40,     /*  [ *]  */
        0x40,     /*  [ *]  */
        0x00,     /*  [  ]  */
        0x00,     /*  [  ]  */
        0x00,     /*  [  ]  */
        0x00,     /*  [  ]  */
        0x00,     /*  [  ]  */
        
        /* char: '.' hexcode: 0x0621 glyph_width: 5 black_width: 5 origin_x: 0 */
        0x00,     /*  [     ]  */
        0x00,     /*  [     ]  */
        0x00,     /*  [     ]  */
        0x00,     /*  [     ]  */
        0x00,     /*  [     ]  */
        0x30,     /*  [  ** ]  */
        0x70,     /*  [ *** ]  */
        0x40,     /*  [ *   ]  */
        0x38,     /*  [  ***]  */
        0x40,     /*  [ *   ]  */
        0x00,     /*  [     ]  */
        0x00,     /*  [     ]  */
        0x00,     /*  [     ]  */
        
        /* char: '.' hexcode: 0xFE8E glyph_width: 3 black_width: 3 origin_x: 0 */
        0x00,     /*  [   ]  */
        0x00,     /*  [   ]  */
        0x00,     /*  [   ]  */
        0x00,     /*  [   ]  */
        0x40,     /*  [ * ]  */
        0x40,     /*  [ * ]  */
        0x40,     /*  [ * ]  */
        0x60,     /*  [ **]  */
        0x20,     /*  [  *]  */
        0x00,     /*  [   ]  */
        0x00,     /*  [   ]  */
        0x00,     /*  [   ]  */
        0x00,     /*  [   ]  */
        
        /* char: '.' hexcode: 0xFE91 glyph_width: 3 black_width: 4 origin_x: -1 */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x10,     /*  [   *]  */
        0x00,     /*  [    ]  */
        0x70,     /*  [ ***]  */
        0x70,     /*  [ ***]  */
        0x00,     /*  [    ]  */
        0x30,     /*  [  **]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        
        /* char: '.' hexcode: 0x0628 glyph_width: 7 black_width: 7 origin_x: 0 */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x02,     /*  [      *]  */
        0x00,     /*  [       ]  */
        0x7E,     /*  [ ******]  */
        0x7E,     /*  [ ******]  */
        0x00,     /*  [       ]  */
        0x08,     /*  [    *  ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        
        /* char: '.' hexcode: 0xFB58 glyph_width: 3 black_width: 4 origin_x: -1 */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x10,     /*  [   *]  */
        0x00,     /*  [    ]  */
        0x70,     /*  [ ***]  */
        0x70,     /*  [ ***]  */
        0x00,     /*  [    ]  */
        0x30,     /*  [  **]  */
        0x10,     /*  [   *]  */
        0x00,     /*  [    ]  */
        
        /* char: '.' hexcode: 0x067E glyph_width: 7 black_width: 7 origin_x: 0 */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x02,     /*  [      *]  */
        0x00,     /*  [       ]  */
        0x7E,     /*  [ ******]  */
        0x7E,     /*  [ ******]  */
        0x00,     /*  [       ]  */
        0x18,     /*  [   **  ]  */
        0x08,     /*  [    *  ]  */
        0x00,     /*  [       ]  */
        
        /* char: '.' hexcode: 0xFE97 glyph_width: 3 black_width: 4 origin_x: -1 */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x30,     /*  [  **]  */
        0x00,     /*  [    ]  */
        0x10,     /*  [   *]  */
        0x00,     /*  [    ]  */
        0x70,     /*  [ ***]  */
        0x70,     /*  [ ***]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        
        /* char: '.' hexcode: 0x062A glyph_width: 7 black_width: 7 origin_x: 0 */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x18,     /*  [   **  ]  */
        0x02,     /*  [      *]  */
        0x00,     /*  [       ]  */
        0x7E,     /*  [ ******]  */
        0x7E,     /*  [ ******]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        
        /* char: '.' hexcode: 0xFE9B glyph_width: 3 black_width: 4 origin_x: -1 */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x20,     /*  [  * ]  */
        0x30,     /*  [  **]  */
        0x00,     /*  [    ]  */
        0x10,     /*  [   *]  */
        0x00,     /*  [    ]  */
        0x70,     /*  [ ***]  */
        0x70,     /*  [ ***]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        0x00,     /*  [    ]  */
        
        /* char: '.' hexcode: 0x062B glyph_width: 7 black_width: 7 origin_x: 0 */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x10,     /*  [   *   ]  */
        0x18,     /*  [   **  ]  */
        0x02,     /*  [      *]  */
        0x00,     /*  [       ]  */
        0x7E,     /*  [ ******]  */
        0x7E,     /*  [ ******]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        
        /* char: '.' hexcode: 0xFE9F glyph_width: 6 black_width: 7 origin_x: -1 */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x18,     /*  [   **  ]  */
        0x0C,     /*  [    ** ]  */
        0x7E,     /*  [ ******]  */
        0x7E,     /*  [ ******]  */
        0x00,     /*  [       ]  */
        0x18,     /*  [   **  ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        
        /* char: '.' hexcode: 0xFE9E glyph_width: 6 black_width: 7 origin_x: 0 */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x7C,     /*  [ ***** ]  */
        0x30,     /*  [  **   ]  */
        0x6C,     /*  [ ** ** ]  */
        0x4C,     /*  [ *  ** ]  */
        0x30,     /*  [  **   ]  */
        0x40,     /*  [ *     ]  */
        0x7C,     /*  [ ***** ]  */
        0x38,     /*  [  ***  ]  */
        
        /* char: '.' hexcode: 0x062C glyph_width: 6 black_width: 7 origin_x: 0 */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x7C,     /*  [ ***** ]  */
        0x20,     /*  [  *    ]  */
        0x40,     /*  [ *     ]  */
        0x18,     /*  [   **  ]  */
        0x00,     /*  [       ]  */
        0x40,     /*  [ *     ]  */
        0x7C,     /*  [ ***** ]  */
        0x38,     /*  [  ***  ]  */
        
        /* char: '.' hexcode: 0xFB7C glyph_width: 6 black_width: 7 origin_x: -1 */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x18,     /*  [   **  ]  */
        0x0C,     /*  [    ** ]  */
        0x7E,     /*  [ ******]  */
        0x7E,     /*  [ ******]  */
        0x00,     /*  [       ]  */
        0x18,     /*  [   **  ]  */
        0x08,     /*  [    *  ]  */
        0x00,     /*  [       ]  */
        
        /* char: '.' hexcode: 0xFB7B glyph_width: 6 black_width: 7 origin_x: 0 */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x7C,     /*  [ ***** ]  */
        0x30,     /*  [  **   ]  */
        0x6C,     /*  [ ** ** ]  */
        0x4C,     /*  [ *  ** ]  */
        0x70,     /*  [ ***   ]  */
        0x50,     /*  [ * *   ]  */
        0x7C,     /*  [ ***** ]  */
        0x38,     /*  [  ***  ]  */
        
        /* char: '.' hexcode: 0x0686 glyph_width: 6 black_width: 7 origin_x: 0 */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x00,     /*  [       ]  */
        0x7C,     /*  [ ***** ]  */
        0x20,     /*  [  *    ]  */
        0x40,     /*  [ *     ]  */
        0x38,     /*  [  ***  ]  */
        0x08,     /*  [    *  ]  */
        0x40,     /*  [ *     ]  */
        0x7C,     /*  [ ***** ]  */
        0x38,     /*  [  ***  ]  */
        
};


#ifdef FONTGEN_USE_PRECALCULATED_OFFSETS
/* Following array provides the starting offset of each glyph in the 
   font_Times_New_Roman_8_n_bnnn_0_nh_glyph_table[].
   
   These offsets can be calculated by code on the micro, but it will require
   some realtime. Using precalculated offsets will work faster, but will require
   more code space.
   
   If you prefer to reduce code size, undefine FONTGEN_USE_PRECALCULATED_OFFSETS.
   If you prefer the code to work faster, define FONTGEN_USE_PRECALCULATED_OFFSETS.
   
   You should index this array with the index of the char in your character set.
   This can be calculated with a simple mathematical expression if you have such
   a simple expression, or you can use the mapping table for this purpose.
   
   To find the starting offset of the glyph in font_Times_New_Roman_8_n_bnnn_0_nh_glyph_table[],
   use the following expression:
       font_Times_New_Roman_8_n_bnnn_0_nh_glyph_table[font_Times_New_Roman_8_n_bnnn_0_nh_offset_table[c]]
   where 'c' is the variable holding the character you're interested in
 */
const font_offset_t font_Times_New_Roman_8_n_bnnn_0_nh_offset_table[] = {
/*        offset  char hexcode*/
/*        ======  ==== =======*/
           0, /* '.' 0x06F0 */
          13, /* '.' 0x06F1 */
          26, /* '.' 0x06F2 */
          39, /* '.' 0x06F3 */
          52, /* '.' 0x06F4 */
          65, /* '.' 0x06F5 */
          78, /* '.' 0x06F6 */
          91, /* '.' 0x06F7 */
         104, /* '.' 0x06F8 */
         117, /* '.' 0x06F9 */
         130, /* '.' 0x0622 */
         143, /* '.' 0x0627 */
         156, /* '.' 0x0621 */
         169, /* '.' 0xFE8E */
         182, /* '.' 0xFE91 */
         195, /* '.' 0x0628 */
         208, /* '.' 0xFB58 */
         221, /* '.' 0x067E */
         234, /* '.' 0xFE97 */
         247, /* '.' 0x062A */
         260, /* '.' 0xFE9B */
         273, /* '.' 0x062B */
         286, /* '.' 0xFE9F */
         299, /* '.' 0xFE9E */
         312, /* '.' 0x062C */
         325, /* '.' 0xFB7C */
         338, /* '.' 0xFB7B */
         351, /* '.' 0x0686 */
};
#endif
